go get -u github.com/kardianos/govendor
go get -u golang.org/x/sys/unix
go get -u golang.org/x/crypto/acme
go get -u golang.org/x/net
go get -u golang.org/x/text
go get -u golang.org/x/tools/go/ast/astutil
go get -u golang.org/x/tools/go/buildutil
go get -u golang.org/x/tools/go/internal/cgo
go get -u golang.org/x/tools/go/loader